[package]
name = "drivers"
version = "0.1.0"
authors = ["Valerii Timakov <valtimakov@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.4"
crc-any = { version = "2.3.5", default-features = false }
defmt = "0.3.5"

[dev-dependencies]
embedded-hal-mock = "0.9.0"
